spring.application.name=reenamart-backend

spring.datasource.url=jdbc:mysql://localhost:3306/reenamart
spring.datasource.username=root
spring.datasource.password=ReenaJency@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true